/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DemoBlock: typeof import('./components/DemoBlock.vue')['default']
    GlobalDialog: typeof import('./components/GlobalDialog.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    HgtConfirmDialog: typeof import('./components/HgtConfirmDialog.vue')['default']
    HgtParticleBackground: typeof import('./components/HgtParticleBackground.vue')['default']
    HgtShell: typeof import('./components/HgtShell.vue')['default']
    HgtThemeTransition: typeof import('./components/HgtThemeTransition.vue')['default']
    PlayerAuthParticleBackground: typeof import('./components/player/AuthParticleBackground.vue')['default']
    PlayerPlayerAuth: typeof import('./components/player/PlayerAuth.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup.vue')['default']
    UniEcharts: typeof import('uni-echarts')['default']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
    WdCell: typeof import('@wot-ui/ui/components/wd-cell/wd-cell.vue')['default']
    WdCellGroup: typeof import('@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue')['default']
    WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['default']
    WdDialog: typeof import('@wot-ui/ui/components/wd-dialog/wd-dialog.vue')['default']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['default']
    WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['default']
    WdNotify: typeof import('@wot-ui/ui/components/wd-notify/wd-notify.vue')['default']
    WdPopup: typeof import('@wot-ui/ui/components/wd-popup/wd-popup.vue')['default']
    WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['default']
    WdTextarea: typeof import('@wot-ui/ui/components/wd-textarea/wd-textarea.vue')['default']
    WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['default']
  }
}
